<!doctype html>
<html lang="ru">
<head>
	<noscript><meta http-equiv="refresh" content="0; URL='/noscript.html'" /></noscript>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<!-- Шрифт Open Sans -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
	<!-- Внешний вид страницы -->
	<link rel="stylesheet" href="/stylesheets/skin.css" />
	<!-- Анимация страницы -->
	<link rel="stylesheet" href="/stylesheets/anim.css" />
	<!-- Дополнительные стили для панели администратора -->
	<link rel="stylesheet" href="/stylesheets/admin.css" />
	<!-- Глифы FontAwesome -->
	<script defer src="https://use.fontawesome.com/releases/v5.0.1/js/all.js"></script>
	<!-- Структурный скрипт страницы -->
	<script src="/scripts/pager.js"></script>
	<!-- Скрипт запросов к серверу -->
	<script src="/scripts/requestor.js"></script>
	<title>: Информатика-Плюс</title>
</head>
<body>
  <div id="form">
  <form>
    <label for="user">Логин</label><br/>
    <input id="user" class="form-textfield form-input-wide" type="text" placeholder="user" /><br/>
    <label for="password">Пароль</label><br/>
    <input id="password" class="form-textfield form-input-wide" type="password" placeholder="password" /><br/>
    <br/><button id="submit" class="shadow" onclick="login()">Войти</button>
  </form>
  </div>
  <script>
    function login(){
      "use strict";
      var form = document.getElementById("form");
      var login = document.getElementById("user").value;
      var password = document.getElementById("password").value;
      if(login!==""&&password!==""){ 
        var request = "login="+login+"&password="+password;
        var req = new XMLHttpRequest();
        req.open("POST","/backbone/login.php");
        req.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        req.send(request);
        req.onload = function(){
          var response = JSON.parse(this.responseText);
          if(response.status==="OK"){
            var ref = location.search;
            ref = ref.substr(5, ref.length-5);
            if(ref==="admin"&&response.priv==="admin") {location.replace("/admin");}
            else {location.replace("/?p=home");}
          }
          else { 
            password = document.getElementById("password");
            password.value = "";
            var error = document.createElement("p");
            error.style.color = "red";
            error.innerText = "Неверный логин или пароль";
            form.insertBefore(error, password.nextSibling);
            password.addEventListener("focus", function(){ if(form.contains(error)){ form.removeChild(error); } })
          }
        }
      }
    }
  </script>
</body>
</html>