<div class="accordion" onMouseEnter="pullAccordion(this)" onMouseLeave="pushAccordion(this)">
	<div class="accordion-header" onClick="toggleAccordion(this, 'self')">
		<p>Гармошка</p>
		<span class="fas fa-chevron-circle-down accordion-toggle-glyph"></span>
	</div>
	<div class="accordion-content hidden">
		
	</div>
	<div class="accordion-content-placeholder">
	</div>
	<div class="accordion-footer">
	</div>
</div>