<div class="newscard">
	<div class="newscard-header centered">
		<h1></h1>
	</div>
	<hr class="horizontal-separator" />
	<div class="newscard-content clear-float">
	</div>
	<hr class="horizontal-separator" />
	<div class="newscard-footer">
		<div class="left">
			<span class="pagination-book" title="Еще новости" onclick="switchNews('newer')"><img src="/pictures/pagination-left.png"></span><span class="pagination-book" title="Еще новости" onclick="switchNews('older')"><img src="/pictures/pagination-right.png"></span>
		</div><div class="right"></div>
	</div>
</div>