<table id="appList">
  <caption>Список заявок</caption>
  <tr><th data-content="ФИО">ФИО</th><th data-content="Телефон">Телефон</th><th data-content="Курс">Курс</th><th data-content="Время">Удобное время</th><th data-content="ДР">Дата рождения</th><th data-content="Заявка">Дата заявки</th><th></th></tr>
</table>
<script>getApplicationsList();</script>
<br/><button id="submit" class="shadow" onclick="requestDeletion(appList,'applications');">Удалить выбранные записи</button>