<div id="templateContainer">
  <div class="showcase card">
  	<img src="" />
  	<div class="textarea">
  		<h4 class="centered"></h4>
  	</div>
  </div>
</div>
<script>setTitle("О нас");</script>
<h1 class="centered">О нас</h1>
<br/>
<h3 class="padding-top">О предприятии</h3>
<p class="margin-top">Наш учебный центр - одно из первых учебных заведений города Новороссийск, обучающих своих слушателей новым информационным технологиям.</p>
<p class="margin-top">МП "Информатика" было образовано в 1989 году и начало с того, что обучало пользователей работе с компьютерами. Проходит время, меняются названия, но желание помочь нашим слушателям остается неизменным и по сей день. Более двадцати пяти лет мы изучаем различные технологии, чтобы донести их вам в наиболее простом и понятном формате.</p>
<h3 class="padding-top">О преподавателях</h3>
<p class="margin-top">Преподаватели нашего методического центра - не новички в своем деле. Наша главная цель - помочь вам освоить навыки, необходимые в той или иной сфере деятельности, связанной с компьютерной техникой. Успешность освоения учебного материала зависит от желания обучаться самих слушателей. В связи с ограниченной длительностью учебных курсов мы не можем успеть поведать нашим слушателям все секреты, но мы стараемся привить им интерес к выбранному ими делу и подтолкнуть их к самосовершенствованию.</p>
<div id="employees" class="flex-stretch-medium flex-wrap"></div>
<script>requestDataFileContents(processStaffList,"team");</script>
<br />
<h3 class="padding-top">Нормативные документы</h3><br/>
<a href="/assets/charter-2017.pdf" target="_blank">Устав ЧОУ ДПО "УМЦ Информатика-Плюс"</a><br/>
<a href="/assets/license.pdf" target="_blank">Лицензия на осуществление образовательной деятельности</a><br/>
<a href="/assets/pay-services.pdf" target="_blank">Положение об оказании образовательных услуг</a><br/>
<a href="/assets/price.pdf" target="_blank">Прайс-лист</a><br/>
<a href="/assets/educational-contract.pdf" target="_blank">Договор об обучении</a><br/>
<a href="/assets/1c-partner.jpg" target="_blank">Сертификат партнерства фирмы 1С</a><br/>
<h3 class="padding-top">О сайте</h3>
<p class="margin-top">Сайт <strong>информатикаплюс.рф</strong>, текущая версия 2.1.17.12 от 28.12.2017.</p>
<p class="margin-top">Создание и поддержка сайта: ЧОУ ДПО "УМЦ Информатика-Плюс".</p>
<p class="margin-top">На сайте использованы глифы из коллекции <a href="https://fontawesome.com" target="_blank">Font Awesome</a> версии 5.0.</p>
<p class="margin-top">На сайте используется шрифт <a href="https://fonts.google.com/specimen/Open+Sans" target="_blank">Open Sans</a> из коллекции веб-шрифтов Google Fonts.</p>