<script>setTitle("Софт");</script>
<h1 class="centered">Программное обеспечение</h1>
<p class="margin-top-bottom">ЧОУ ДПО "УМЦ Информатика-Плюс" является официальным дистрибьютором программного обеспечения компаний 1С, Adobe, Microsoft, Autodesk. Вы можете заказать у нас не только сами программы, но также настройку и техническую поддержку этих программ.</p>
<div class="flex-stretch-medium flex-wrap">
  <div class="showcase card">
	  <img src="/pictures/brands/adobe.jpg" />
	  <div class="textarea">
      <h4 class="centered">Adobe</h4>
      <p class="justified">Компания, разрабатывающая широ&shy;кий спектр программ, связанных с компьютерной графикой, анимацией, обработкой видео, аудио и веб-технологиями.</p>
      <p>Например:</p>
      <ul class="unmarked">
        <li><a href="http://www.adobe.com/ru/products/photoshop.html" target="_blank">Adobe Photoshop</a></li>
        <li><a href="http://www.adobe.com/ru/products/animate.html" target="_blank">Adobe Animate</a></li>
        <li><a href="http://www.adobe.com/ru/products/dreamweaver.html" target="_blank">Adobe Dreamweaver</a></li>
        <li><a href="http://www.adobe.com/ru/products/illustrator.html" target="_blank">Adobe Illustrator</a></li>
      </ul>
	  </div>
  </div>
  <div class="showcase card">
	  <img src="/pictures/brands/autodesk.jpg" />
	  <div class="textarea">
      <h4 class="centered">Autodesk</h4>
      <p class="justified">Разработчик систем автоматизи&shy;рованного проектирования, исполь&shy;зуемых инженерами, архитекторами, дизайнерами и другими специалис&shy;тами.</p>
      <p>Например:</p>
      <ul class="unmarked">
        <li><a href="https://www.autodesk.ru/products/autocad/overview" target="_blank">Autodesk AutoCAD</a></li>
        <li><a href="https://www.autodesk.ru/products/3ds-max/overview" target="_blank">Autodesk 3ds Max</a></li>
        <li><a href="https://www.autodesk.ru/products/maya/overview" target="_blank">Autodesk Maya</a></li>
        <li><a href="https://www.autodesk.ru/products/revit-family/overview" target="_blank">Autodesk Revit</a></li>
      </ul>
	  </div>
  </div>
  <div class="showcase card">
	  <img src="/pictures/brands/microsoft.jpg" />
	  <div class="textarea">
      <h4 class="centered">Microsoft</h4>
      <p class="justified">Разработчик семейства операцион&shy;ных систем Windows, пакета офисных приложений MS Office, и не только. Программы Microsoft используются для личных и деловых целей.</p>
      <p>Например:</p>
      <ul class="unmarked">
        <li><a href="https://www.microsoft.com/ru-ru/windows/" target="_blank">ОС Windows</a></li>
        <li><a href="https://www.microsoft.com/ru-ru/cloud-platform/windows-server" target="_blank">Windows Server</a></li>
        <li><a href="https://products.office.com/ru-ru/home" target="_blank">Microsoft Office</a></li>
        <li><a href="https://dynamics.microsoft.com/ru-ru/" target="_blank">Microsoft Dynamics</a></li>
      </ul>
	  </div>
  </div>
  <div class="showcase card">
	  <img src="/pictures/brands/1C.jpg" />
	  <div class="textarea">
      <h4 class="centered">1C</h4>
      <p class="justified">Фирма "1С" специализируется на разработке, дистрибьюции, издании и поддержке компьютерных про&shy;грамм делового и домашнего назначения.</p>
      <p>Например:</p>
      <ul class="unmarked">
        <li><a href="http://v8.1c.ru/buhv8/" target="_blank">1С: Бухгалтерия</a></li>
        <li><a href="http://v8.1c.ru/trade/" target="_blank">1С: Управление торговлей</a></li>
        <li><a href="http://v8.1c.ru/hrm/" target="_blank">1С: Зарплата и кадры</a></li>
        <li><a href="http://obr.1c.ru/educational/catalog/" target="_blank">Образовательные программы</a></li>
      </ul>
	  </div>
  </div>
</div>
<br/>